spring.application.name=gestion_de_note
# 1. URL ديال الداتابيس gestion
server.port=9000

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/gestion?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# Affiche les valeurs dyal les paramètres SQL f console (Useful for debugging)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.main.allow-bean-definition-overriding=true